// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wx.demo.frameWork.proto;

public interface BaseMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WechatProto.BaseMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ret = 1;</code>
   */
  int getRet();

  /**
   * <code>int32 cmd = 2;</code>
   */
  int getCmd();

  /**
   * <code>string cmdUrl = 3;</code>
   */
  String getCmdUrl();
  /**
   * <code>string cmdUrl = 3;</code>
   */
  com.google.protobuf.ByteString
      getCmdUrlBytes();

  /**
   * <code>string shortHost = 4;</code>
   */
  String getShortHost();
  /**
   * <code>string shortHost = 4;</code>
   */
  com.google.protobuf.ByteString
      getShortHostBytes();

  /**
   * <code>string longHost = 5;</code>
   */
  String getLongHost();
  /**
   * <code>string longHost = 5;</code>
   */
  com.google.protobuf.ByteString
      getLongHostBytes();

  /**
   * <code>.WechatProto.User user = 6;</code>
   */
  boolean hasUser();
  /**
   * <code>.WechatProto.User user = 6;</code>
   */
  User getUser();
  /**
   * <code>.WechatProto.User user = 6;</code>
   */
  UserOrBuilder getUserOrBuilder();

  /**
   * <code>bytes longHead = 7;</code>
   */
  com.google.protobuf.ByteString getLongHead();

  /**
   * <code>bytes payloads = 8;</code>
   */
  com.google.protobuf.ByteString getPayloads();

  /**
   * <code>bytes playloadextend = 9;</code>
   */
  com.google.protobuf.ByteString getPlayloadextend();
}
