// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wx.demo.frameWork.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WechatProto.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uin = 1;</code>
   */
  long getUin();

  /**
   * <code>bytes cookies = 2;</code>
   */
  com.google.protobuf.ByteString getCookies();

  /**
   * <code>bytes sessionKey = 3;</code>
   */
  com.google.protobuf.ByteString getSessionKey();

  /**
   * <code>string deviceId = 4;</code>
   */
  String getDeviceId();
  /**
   * <code>string deviceId = 4;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string deviceType = 5;</code>
   */
  String getDeviceType();
  /**
   * <code>string deviceType = 5;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <code>string deviceName = 6;</code>
   */
  String getDeviceName();
  /**
   * <code>string deviceName = 6;</code>
   */
  com.google.protobuf.ByteString
      getDeviceNameBytes();

  /**
   * <code>bytes currentsyncKey = 7;</code>
   */
  com.google.protobuf.ByteString getCurrentsyncKey();

  /**
   * <code>bytes maxSyncKey = 8;</code>
   */
  com.google.protobuf.ByteString getMaxSyncKey();

  /**
   * <code>bytes autoAuthKey = 9;</code>
   */
  com.google.protobuf.ByteString getAutoAuthKey();

  /**
   * <code>string userame = 10;</code>
   */
  String getUserame();
  /**
   * <code>string userame = 10;</code>
   */
  com.google.protobuf.ByteString
      getUserameBytes();

  /**
   * <code>bytes nickname = 11;</code>
   */
  com.google.protobuf.ByteString getNickname();

  /**
   * <code>bytes userExt = 12;</code>
   */
  com.google.protobuf.ByteString getUserExt();
}
