// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WechatProto.proto

package com.wx.demo.frameWork.proto;

public interface WechatMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WechatProto.WechatMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.WechatProto.BaseMsg baseMsg = 1;</code>
   */
  boolean hasBaseMsg();
  /**
   * <code>.WechatProto.BaseMsg baseMsg = 1;</code>
   */
  BaseMsg getBaseMsg();
  /**
   * <code>.WechatProto.BaseMsg baseMsg = 1;</code>
   */
  BaseMsgOrBuilder getBaseMsgOrBuilder();

  /**
   * <code>string token = 2;</code>
   */
  String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string version = 3;</code>
   */
  String getVersion();
  /**
   * <code>string version = 3;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>int32 timeStamp = 4;</code>
   */
  int getTimeStamp();

  /**
   * <code>string iP = 5;</code>
   */
  String getIP();
  /**
   * <code>string iP = 5;</code>
   */
  com.google.protobuf.ByteString
      getIPBytes();
}
