/*
 * 微信协议 API
 * 说明 [http://swagger.io](http://swagger.io)  swagger [22222](http://swagger.io/irc/). key `123` to test .
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@wxipad.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wx.demo.wechatapi.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * grpc消息参数
 */
@ApiModel(description = "grpc消息参数")
public class WechatMsg {
  @SerializedName("Token")
  private String token = null;

  @SerializedName("Version")
  private String version = null;

  @SerializedName("TimeStamp")
  private Integer timeStamp = null;

  @SerializedName("ip")
  private String ip = null;

  @SerializedName("baseMsg")
  private UtilBase baseMsg = null;

  public WechatMsg token(String token) {
    this.token = token;
    return this;
  }

   /**
   * 授权密钥（v3_xxxxxxxxxx）
   * @return token
  **/
  @ApiModelProperty(value = "授权密钥（v3_xxxxxxxxxx）")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public WechatMsg version(String version) {
    this.version = version;
    return this;
  }

   /**
   * 微信版本
   * @return version
  **/
  @ApiModelProperty(value = "微信版本")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public WechatMsg timeStamp(Integer timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * 时间戳
   * @return timeStamp
  **/
  @ApiModelProperty(value = "时间戳")
  public Integer getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(Integer timeStamp) {
    this.timeStamp = timeStamp;
  }

  public WechatMsg ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * 真实IP地址
   * @return ip
  **/
  @ApiModelProperty(value = "真实IP地址")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public WechatMsg baseMsg(UtilBase baseMsg) {
    this.baseMsg = baseMsg;
    return this;
  }

   /**
   * 消息体
   * @return baseMsg
  **/
  @ApiModelProperty(value = "消息体")
  public UtilBase getBaseMsg() {
    return baseMsg;
  }

  public void setBaseMsg(UtilBase baseMsg) {
    this.baseMsg = baseMsg;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WechatMsg wechatMsg = (WechatMsg) o;
    return Objects.equals(this.token, wechatMsg.token) &&
        Objects.equals(this.version, wechatMsg.version) &&
        Objects.equals(this.timeStamp, wechatMsg.timeStamp) &&
        Objects.equals(this.ip, wechatMsg.ip) &&
        Objects.equals(this.baseMsg, wechatMsg.baseMsg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, version, timeStamp, ip, baseMsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WechatMsg {\n");

    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    baseMsg: ").append(toIndentedString(baseMsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

